import type { TTerminalLine } from "../utils/types";

export type TReport = {
  name: string;
  report: TTerminalLine[];
};

export const reports: TReport[] = [
  {
    name: "Q1-2064 Financial Summary",
    report: [
      "GUNNARSSON INC. // Q1-2064 FINANCIAL SUMMARY",
      "─────────────────────────────────────────────",
      "Total Revenue:        ¥ 12,450,000",
      "Net Profit:           ¥ 3,210,000",
      "Operating Expenses:   ¥ 7,800,000",
      "R&D Investment:       ¥ 1,200,000",
      "",
      "Top Product: VALHALLA SHEET v4.2",
      "New Corporate Clients: 17",
      "",
      "// Notes:",
      "- Market share in Gothenburg up 12%",
      "- Security breach attempts: 0 (ICE protocols holding)",
      "- Next quarter: Launch of ODIN Analytics Suite",
      "─────────────────────────────────────────────",
      "",
      "Signed: S. Lindholm, CFO",
    ],
  },
  {
    name: "Valhalla SaaS User Metrics",
    report: [
      "VALHALLA SHEET // USER METRICS",
      "─────────────────────────────────────────────",
      "Active Users:         8,420",
      "Concurrent Sessions:  1,120",
      "Avg. Uptime:          99.997%",
      "",
      "Top 3 Corporate Realms:",
      "  1. Yggdrasil Holdings (NO)",
      "  2. Fenrir Logistics (SE)",
      "  3. Valkyrie Dataworks (DE)",
      "",
      "Recent Feature Adoption:",
      "- RAGNAROK Macro Engine: 68%",
      "- BERSERK Mode (Batch Ops): 44%",
      "- Runestone Encryption: 99%",
      "───────────────────────────────────",
      "",
      "Sysadmin: THOR-9000",
    ],
  },
  {
    name: "Market Share Trends - Gothenburg",
    report: [
      "GUNNARSSON INC. // MARKET SHARE TRENDS",
      "────────────────────────────────────────────",
      "Region: Gothenburg (Scandinavian Union Capital)",
      "Product: Valhalla Sheet v4.2",
      "",
      "Quarterly Market Share (%)",
      "",
      " Q2-2063   Q3-2063   Q4-2063   Q1-2064",
      <pre>{" ┌────┬────┬────┬────┐"}</pre>,
      <pre>{" │ 22 │ 27 │ 31 │ 43 │"}</pre>,
      <pre>{" └─┬──┴─┬──┴─┬──┴─┬──┘"}</pre>,
      <pre>{"   │    │    │    │     "}</pre>,
      <pre>{"   │    │    │    └────┐"}</pre>,
      <pre>{"   │    │    └──┐      │"}</pre>,
      <pre>{"   │    └─┐     │      │"}</pre>,
      <pre>{"   │      │     │      │"}</pre>,
      <pre>{"   │      │     │      │"}</pre>,
      <pre>{"   ▼      ▼     ▼      ▼"}</pre>,
      <pre> </pre>,
      <pre>{"   █"}</pre>,
      <pre>{"   █     █"}</pre>,
      <pre>{"   █     █      █"}</pre>,
      <pre>{"   █     █      █      █"}</pre>,
      <pre>{"──────────────────────────"}</pre>,
      "",
      "Annual Revenue (¥, millions)",
      "",
      <pre>{" 2061  2062  2063  2064"}</pre>,
      <pre> </pre>,
      <pre>{" ███   ████  █████ ███████"}</pre>,
      <pre> </pre>,
      <pre>{"  48    57    68     92"}</pre>,
      "────────────────────────────────",
      "",
      "Analyst: Sigrun E. (Data Seer)",
    ],
  },
  {
    name: "Viking Legacy Project",
    report: [
      "GUNNARSSON INC. // VIKING LEGACY PROJECT",
      "─────────────────────────────────────────────",
      "Project: Digital Longship",
      "Year: 2064",
      "",
      "Celebrating our Nordic roots with cutting-edge tech.",
      "",
      <pre>{"                ~.                     "}</pre>,
      <pre>{"          Ya...___|__..ab.     .   .   "}</pre>,
      <pre>{"           Y88b  \\88b  \\88b   (     )  "}</pre>,
      <pre>{"            Y88b  :88b  :88b   `.oo'   "}</pre>,
      <pre>{"            :888  |888  |888  ( (`-'   "}</pre>,
      <pre>{"   .---.    d88P  ;88P  ;88P   `.`.    "}</pre>,
      <pre>{'  / .-._)  d8P-"""|"""\'-Y8P      `.`.  '}</pre>,
      <pre>{" ( (`._) .-.  .-. |.-.  .-.  .-.   ) ) "}</pre>,
      <pre>{"  \\ `---( O )( O )( O )( O )( O )-' /  "}</pre>,
      <pre>{"   `.    `-'  `-'  `-'  `-'  `-'  .' CJ "}</pre>,
      <pre>{"     `---------------------------'"}</pre>,
      "",
      "- New educational modules launched for Valhalla Sheet",
      "- Partnership with Gothenburg Maritime Museum",
      "- Employee event: Virtual Raid Simulation",
      "",
      "─────────────────────────────────────────────",
      "",
      "Contact: Freya S. (Culture & Outreach)",
    ],
  },
];
